namhai923/Bison-Bank-of-Canada

README.md
=> add paragraph to summary

back-end/cache.js, back-end/models/User.js, back-end/routes/admin/index.js, back-end/routes/index.js, back-end/routes/user/index.js
Add cache and new endpoints for getting user data and accepting transaction record #24 #29
=> Add cache and new endpoints

back-end/index.js, back-end/models/User.js, back-end/routes/admin/index.js, back-end/routes/user/index.js
Added endpoints for transferring money
Changed schema for accountBalance and amount in both transfer history and expenseHistory to be decimal
Changed how we handle money through sending a record (use math.round for subtracting money for precision)
#34 #35
=> Add endpoint for transferring money, bug fix

front-end/src/views/dashboard/Default/PopularCard.js, front-end/src/views/dashboard/Default/index.js
Added table that is able to display the user's expense. (Note: at this moment is not connected to our database and cannot display the actual data)
=> Added table that displays the user's expenses to the front end

front-end/src/views/dashboard/Default/PopularCard.js
Divided User Expense Table into sections (ex. display 10 at a time) to make it easier to view. Also got rid of some existing warnings
https://github.com/namhai923/Bison-Bank-of-Canada/issues/46
=> Front End: Added Sections for User Expense Table and got rid of warnings

front-end/src/layout/MainLayout/Header/WelcomeSection/index.js, front-end/src/views/dashboard/Default/PopularCard.js
https://github.com/namhai923/Bison-Bank-of-Canada/issues/50
https://github.com/namhai923/Bison-Bank-of-Canada/issues/51
=>  Connected Expense Table to database and Changed shade of yellow for medium transaction in expense table

back-end/index.js, back-end/package.json, back-end/src/config/index.config.js, back-end/src/connection.js, back-end/src/routes/user/index.routes.js, back-end/src/tests/admin.test.js, back-end/src/tests/user.test.js
Add unit tests for existing endpoints #38
=> Added unit tests for couple endpoints

back-end/src/__test__/routes/admin/admin.test.js, back-end/src/__test__/routes/user/user.test.js, back-end/src/routes/admin/index.routes.js, back-end/src/routes/user/index.routes.js
=> Add unit test and more checks for Endpoints

front-end/src/views/dashboard/Default/PopularCard.js
Related to [Issue #66](https://github.com/namhai923/Bison-Bank-of-Canada/issues/66)
=> Removed extra code from PopularCard.js

README.md
Added instructions on how to use product to ReadMe for ease of use
=> Added some Instructions to ReadMe

.github/workflows/backend_testing.yml, README.md
Added new feature description to readme file
=> add new feature to readme

back-end/package.json, back-end/src/__test__/routes/admin/admin.test.js, back-end/src/__test__/routes/user/user.test.js, back-end/src/routes/admin/index.routes.js, back-end/src/routes/user/index.routes.js
Added check for invalid request body and add unit test for it
Now npm test shows test coverage
#68
=> Add more unit tests for backend

front-end/src/routes/AuthenticationRoutes.js, front-end/src/views/pages/authentication/auth-forms/AuthTransferMoney.js, front-end/src/views/pages/authentication/auth-template/TransferMoney.js
https://github.com/namhai923/Bison-Bank-of-Canada/issues/86
=> added UI for transfer money

.github/workflows/frontend_testing.yml, front-end/package-lock.json
Update the the backend pipeline and add frontend pipeline
=> Update CI pipeline for both back and front end

back-end/src/__test__/cache.test.js, back-end/src/__test__/routes/admin/admin.test.js, back-end/src/__test__/routes/user/user.test.js, back-end/src/cache.js, back-end/src/routes/admin/index.routes.js, back-end/src/routes/user/index.routes.js
#84 
Added cache
Cache will be set for the first time when a user logs in, then it will expire after 300 seconds
Added unit tests for it
=> Add cache and unit test for it

back-end/src/__test__/routes/user/user.test.js, back-end/src/routes/user/index.routes.js
Update transfer to return sender info
Updated related unit test
=> Update transfer to return sender info

.github/workflows/deploy.yml, back-end/Dockerfile, front-end/Dockerfile
#94 
Try to add the CD pipeline
=> Add docker files and deploy yaml

front-end/src/store/index.js, front-end/src/ui-component/cards/ListCard.js, front-end/src/views/banking/dashboard/FilterModal.js, front-end/src/views/banking/dashboard/filterSlice.js, front-end/src/views/banking/history/ExpenseHistory.js
Completed the filter feature.
Right now, it is filtering based on "Location" and "Category." I will add "filter by date" in the future if time permits.
=> Filter feature part 2

front-end/src/tests/expenseHistory.test.js, front-end/src/tests/sendMoney.test.js, front-end/src/tests/transferHistory.test.js, front-end/src/views/banking/send-money/Transfer.js
https://github.com/namhai923/Bison-Bank-of-Canada/issues/113
=> added user test for sbhowing user expense

back-end/src/__test__/integtation/admin/admin.test.js, back-end/src/__test__/integtation/expense/expense.test.js, back-end/src/__test__/integtation/transfer/transferMoney.test.js, back-end/src/__test__/integtation/users/userProfile.test.js, back-end/src/__test__/integtation/users/users.test.js, package-lock.json
Added integration tests. Relating to this issue - [#140 ](https://github.com/namhai923/Bison-Bank-of-Canada/issues/140)
=> Integration tests

.gitignore, README.md, Test Plan.md, back-end/.env, front-end/.env
add environment files to front/back end folder and minor fixes to README and Test Plan
=> add environment files
